version: "1"
services:
  - name: backpackregistrychecklistspostgres
    image: 'postgres:11.5'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lists
    ports:
      - '5432:5432'
  - name: zookeeper
    image: 'wurstmeister/zookeeper:3.4.6'
    ports:
      - '2181:2181'
  - name: kafka
    image: 'wurstmeister/kafka:2.12-2.3.0'
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISE_HOST_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: lists-msg-bus:1:1,lists-dlq:1:1

steps:
  - name: restore_cache
    image: docker.target.com/vela-plugins/s3-cache:v0.5.1-1
    secrets: [ cache_s3_access_key, cache_s3_secret_key, cache_s3_server ]
    parameters:
      action: restore

  - name: publish-config-backpack-registrychecklists-dev
    ruleset:
      event: [ push ]
      branch: master
    image: 'docker.target.com/app/lists/alpine-bash-curl-ssl:1.0.5'
    environment:
      CICD_MODE: 'true'
    secrets:
      - TAP_API_TOKEN
    commands:
      - export BACKPACK_REGISTRYCHECKLISTS_APP_PRIVATE_KEY_DEV=$(cat /vela/secrets/backpack_registrychecklists_app_private_key_dev/privkey)
      - tap_api_token=$TAP_API_TOKEN app_private_key=$BACKPACK_REGISTRYCHECKLISTS_APP_PRIVATE_KEY_DEV ./backpack-registrychecklists-app/scripts/config_deploy_manager.sh conf.dev.0.0
      - export BACKPACK_REGISTRYCHECKLISTS_CONSUMER_APP_PRIVATE_KEY_DEV=$(cat /vela/secrets/backpack_registrychecklists_consumer_app_private_key_dev/privkey)
      - tap_api_token=$TAP_API_TOKEN app_private_key=$BACKPACK_REGISTRYCHECKLISTS_CONSUMER_APP_PRIVATE_KEY_DEV ./backpack-registrychecklists-consumer-app/scripts/config_deploy_manager.sh conf.dev.0.0
      - export BACKPACK_REGISTRYCHECKLISTS_MIGRATION_CONSUMER_APP_PRIVATE_KEY_DEV=$(cat /vela/secrets/backpack_registrychecklists_migration_consumer_app_private_key_dev/privkey)
      - tap_api_token=$TAP_API_TOKEN app_private_key=$BACKPACK_REGISTRYCHECKLISTS_MIGRATION_CONSUMER_APP_PRIVATE_KEY_DEV ./backpack-registrychecklists-migration-consumer-app/scripts/config_deploy_manager.sh conf.dev.0.0

  - name: publish-config-backpack-registrychecklists-stage
    ruleset:
      event: tag
      tag: conf.stage.backpackregistrychecklists.*
      branch: master
    image: 'docker.target.com/app/lists/alpine-bash-curl-ssl:1.0.5'
    environment:
      CICD_MODE: 'true'
    secrets:
      - TAP_API_TOKEN
    commands:
      - export BACKPACK_REGISTRYCHECKLISTS_APP_PRIVATE_KEY_STAGE=$(cat /vela/secrets/backpack_registrychecklists_app_private_key_stage/privkey)
      - tap_api_token=$TAP_API_TOKEN app_private_key=$BACKPACK_REGISTRYCHECKLISTS_APP_PRIVATE_KEY_STAGE ./backpack-registrychecklists-app/scripts/config_deploy_manager.sh ${BUILD_TAG}
      - export BACKPACK_REGISTRYCHECKLISTS_CONSUMER_APP_PRIVATE_KEY_STAGE=$(cat /vela/secrets/backpack_registrychecklists_consumer_app_private_key_stage/privkey)
      - tap_api_token=$TAP_API_TOKEN app_private_key=$BACKPACK_REGISTRYCHECKLISTS_CONSUMER_APP_PRIVATE_KEY_STAGE ./backpack-registrychecklists-consumer-app/scripts/config_deploy_manager.sh ${BUILD_TAG}
      - export BACKPACK_REGISTRYCHECKLISTS_MIGRATION_CONSUMER_APP_PRIVATE_KEY_STAGE=$(cat /vela/secrets/backpack_registrychecklists_migration_consumer_app_private_key_stage/privkey)
      - tap_api_token=$TAP_API_TOKEN app_private_key=$BACKPACK_REGISTRYCHECKLISTS_MIGRATION_CONSUMER_APP_PRIVATE_KEY_STAGE ./backpack-registrychecklists-migration-consumer-app/scripts/config_deploy_manager.sh ${BUILD_TAG}

  - name: publish-config-backpack-registrychecklists-prod
    ruleset:
      event: tag
      tag: conf.prod.backpackregistrychecklists.*
      branch: master
    image: 'docker.target.com/app/lists/alpine-bash-curl-ssl:1.0.5'
    environment:
      CICD_MODE: 'true'
    secrets:
      - TAP_API_TOKEN
    commands:
      - export BACKPACK_REGISTRYCHECKLISTS_APP_PRIVATE_KEY_PROD=$(cat /vela/secrets/backpack_registrychecklists_app_private_key_prod/privkey)
      - tap_api_token=$TAP_API_TOKEN app_private_key=$BACKPACK_REGISTRYCHECKLISTS_APP_PRIVATE_KEY_PROD ./backpack-registrychecklists-app/scripts/config_deploy_manager.sh ${BUILD_TAG}
      - export BACKPACK_REGISTRYCHECKLISTS_CONSUMER_APP_PRIVATE_KEY_PROD=$(cat /vela/secrets/backpack_registrychecklists_consumer_app_private_key_prod/privkey)
      - tap_api_token=$TAP_API_TOKEN app_private_key=$BACKPACK_REGISTRYCHECKLISTS_CONSUMER_APP_PRIVATE_KEY_PROD ./backpack-registrychecklists-consumer-app/scripts/config_deploy_manager.sh ${BUILD_TAG}
      - export BACKPACK_REGISTRYCHECKLISTS_MIGRATION_CONSUMER_APP_PRIVATE_KEY_PROD=$(cat /vela/secrets/backpack_registrychecklists_migration_consumer_app_private_key_prod/privkey)
      - tap_api_token=$TAP_API_TOKEN app_private_key=$BACKPACK_REGISTRYCHECKLISTS_MIGRATION_CONSUMER_APP_PRIVATE_KEY_PROD ./backpack-registrychecklists-migration-consumer-app/scripts/config_deploy_manager.sh ${BUILD_TAG}

  - name: build
    image: 'docker.target.com/tap/alpine-openjdk11-build:latest'
    ruleset:
      event: [pull_request, push, tag]
    environment:
      JAVA_TOOL_OPTIONS: '-Xmx4000M'
      GRADLE_USER_HOME: .gradle
      GRADLE_OPTS: '-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=1 -Dorg.gradle.parallel=false'
      JDBC_URL: 'jdbc:postgresql://backpackregistrychecklistspostgres:5432/lists'
      KAFKA_BOOTSTRAP_SERVERS: 'kafka:9092'
    commands:
      - 'mkdir -p masterspec'
      - 'git clone https://git.target.com/Registry-Modernization/backpack-registrychecklists --branch master --single-branch masterspec'
      - 'export GIT_MASTER_SPEC_PATH=`pwd`/masterspec'
      - './gradlew build distTar'

  - name: rebuild_cache
    image: docker.target.com/vela-plugins/s3-cache:v0.5.1-1
    ruleset:
      event: [ pull_request, push, tag ]
    secrets: [ cache_s3_access_key, cache_s3_secret_key, cache_s3_server ]
    parameters:
      action: rebuild
      mount:
        - .gradle

  - name: flush_cache
    image: docker.target.com/vela-plugins/s3-cache:v0.5.1-1
    ruleset:
      event: [ pull_request, push, tag ]
    secrets: [ cache_s3_access_key, cache_s3_secret_key, cache_s3_server ]
    parameters:
      action: flush

  - name: publish-docker-backpackregistrychecklists-app-dev
    image: docker.target.com/vela-plugins/kaniko:v0.6.0-1
    pull: always
    parameters:
      registry: docker.target.com
      repo: docker.target.com/app/backpack-registrychecklists/backpack-registrychecklists-app
      dockerfile: ./backpack-registrychecklists-app/Dockerfile
      tags:
        - 'b${BUILD_NUMBER}-${BUILD_COMMIT:0:8}'
        - latest
    ruleset:
      event: [ push ]
      branch: master
    environment:
      CICD_MODE: 'true'
    secrets: [ docker_username, docker_password ]

  - name: publish-docker-backpackregistrychecklists-app-stage
    image: docker.target.com/vela-plugins/kaniko:v0.6.0-1
    pull: not_present
    parameters:
      registry: docker.target.com
      repo: docker.target.com/app/backpack-registrychecklists/backpack-registrychecklists-app
      dockerfile: ./backpack-registrychecklists-app/Dockerfile
      tags: 'rc.${BUILD_TAG:38}'
    ruleset:
      event: tag
      branch: master
      tag: conf.stage.backpackregistrychecklists.*
    environment:
      CICD_MODE: 'true'
    secrets: [ docker_username, docker_password ]

  - name: publish-docker-backpackregistrychecklists-app-prod
    image: docker.target.com/vela-plugins/artifactory:latest
    pull: not_present
    parameters:
      action: docker-promote
      docker_registry: app/backpack-registrychecklists/backpack-registrychecklists-app
      target_docker_registry: app/backpack-registrychecklists/backpack-registrychecklists-app
      tags: "rc.${BUILD_TAG:37}"
    ruleset:
      event: tag
      branch: master
      tag: conf.prod.backpackregistrychecklists.*
    environment:
      CICD_MODE: 'true'
    secrets:
      - source: docker_password
        target: artifactory_password
      - source: docker_username
        target: artifactory_username

  - name: publish-docker-backpackregistrychecklists-consumer-app-dev
    image: docker.target.com/vela-plugins/kaniko:v0.6.0-1
    pull: always
    parameters:
      registry: docker.target.com
      repo: docker.target.com/app/backpack-registrychecklists/backpack-registrychecklists-consumer-app
      dockerfile: ./backpack-registrychecklists-consumer-app/Dockerfile
      tags:
        - 'b${BUILD_NUMBER}-${BUILD_COMMIT:0:8}'
        - latest
    ruleset:
      event: [ push ]
      branch: master
    environment:
      CICD_MODE: 'true'
    secrets: [ docker_username, docker_password ]

  - name: publish-docker-backpackregistrychecklists-consumer-app-stage
    image: docker.target.com/vela-plugins/kaniko:v0.6.0-1
    pull: not_present
    parameters:
      registry: docker.target.com
      repo: docker.target.com/app/backpack-registrychecklists/backpack-registrychecklists-consumer-app
      dockerfile: ./backpack-registrychecklists-consumer-app/Dockerfile
      tags: 'rc.${BUILD_TAG:38}'
    ruleset:
      event: tag
      branch: master
      tag: conf.stage.backpackregistrychecklists.*
    environment:
      CICD_MODE: 'true'
    secrets: [ docker_username, docker_password ]

  - name: publish-docker-backpackregistrychecklists-consumer-app-prod
    image: docker.target.com/vela-plugins/artifactory:latest
    pull: not_present
    parameters:
      action: docker-promote
      docker_registry: app/backpack-registrychecklists/backpack-registrychecklists-consumer-app
      target_docker_registry: app/backpack-registrychecklists/backpack-registrychecklists-consumer-app
      tags: "rc.${BUILD_TAG:37}"
    ruleset:
      event: tag
      branch: master
      tag: conf.prod.backpackregistrychecklists.*
    environment:
      CICD_MODE: 'true'
    secrets:
      - source: docker_password
        target: artifactory_password
      - source: docker_username
        target: artifactory_username

  - name: publish-docker-backpackregistrychecklists-migration-consumer-app-dev
    image: docker.target.com/vela-plugins/kaniko:v0.6.0-1
    pull: always
    parameters:
      registry: docker.target.com
      repo: docker.target.com/app/backpack-registrychecklists/backpack-registrychecklists-migration-consumer-app
      dockerfile: ./backpack-registrychecklists-migration-consumer-app/Dockerfile
      tags:
        - 'b${BUILD_NUMBER}-${BUILD_COMMIT:0:8}'
        - latest
    ruleset:
      event: [ push ]
      branch: master
    environment:
      CICD_MODE: 'true'
    secrets: [ docker_username, docker_password ]

  - name: publish-docker-backpackregistrychecklists-migration-consumer-app-stage
    image: docker.target.com/vela-plugins/kaniko:v0.6.0-1
    pull: not_present
    parameters:
      registry: docker.target.com
      repo: docker.target.com/app/backpack-registrychecklists/backpack-registrychecklists-migration-consumer-app
      dockerfile: ./backpack-registrychecklists-migration-consumer-app/Dockerfile
      tags: 'rc.${BUILD_TAG:38}'
    ruleset:
      event: tag
      branch: master
      tag: conf.stage.backpackregistrychecklists.*
    environment:
      CICD_MODE: 'true'
    secrets: [ docker_username, docker_password ]

  - name: publish-docker-backpackregistrychecklists-migration-consumer-app-prod
    image: docker.target.com/vela-plugins/artifactory:latest
    pull: not_present
    parameters:
      action: docker-promote
      docker_registry: app/backpack-registrychecklists/backpack-registrychecklists-migration-consumer-app
      target_docker_registry: app/backpack-registrychecklists/backpack-registrychecklists-migration-consumer-app
      tags: "rc.${BUILD_TAG:37}"
    ruleset:
      event: tag
      branch: master
      tag: conf.prod.backpackregistrychecklists.*
    environment:
      CICD_MODE: 'true'
    secrets:
      - source: docker_password
        target: artifactory_password
      - source: docker_username
        target: artifactory_username

secrets:
  - name: cache_s3_server
    key: vela/prod-secrets/cache_s3_server
    engine: native
    type: shared
  - name: cache_s3_access_key
    key: vela/prod-secrets/cache_s3_access_key
    engine: native
    type: shared
  - name: cache_s3_secret_key
    key: vela/prod-secrets/cache_s3_secret_key
    engine: native
    type: shared
  - name: TAP_API_TOKEN
    key: Registry-Modernization/TAP_API_TOKEN
    engine: native
    type: org
  - name: vault_username
    key: Registry-Modernization/vault_username
    engine: native
    type: org
  - name: vault_password
    key: Registry-Modernization/vault_password
    engine: native
    type: org
  - name: docker_username
    key: Registry-Modernization/docker_username
    engine: native
    type: org
  - name: docker_password
    key: Registry-Modernization/docker_password
    engine: native
    type: org
  - origin:
      name: vault
      image: docker.target.com/vela-secrets/vault:latest
      pull: always
      secrets: [ vault_username, vault_password ]
      parameters:
        log_level: debug
        items:
          - source: secret/registries-modernization/dev/backpack-registrychecklists/backpackregistrychecklists
            path: backpack_registrychecklists_app_private_key_dev
          - source: secret/registries-modernization/dev/backpack-registrychecklists/backpackregistrychecklistsconsumer
            path: backpack_registrychecklists_consumer_app_private_key_dev
          - source: secret/registries-modernization/dev/backpack-registrychecklists/backpackregistrychecklistsmigrationconsumer
            path: backpack_registrychecklists_migration_consumer_app_private_key_dev
          - source: secret/registries-modernization/stage/backpack-registrychecklists/backpackregistrychecklists
            path: backpack_registrychecklists_app_private_key_stage
          - source: secret/registries-modernization/stage/backpack-registrychecklists/backpackregistrychecklistsconsumer
            path: backpack_registrychecklists_consumer_app_private_key_stage
          - source: secret/registries-modernization/stage/backpack-registrychecklists/backpackregistrychecklistsmigrationconsumer
            path: backpack_registrychecklists_migration_consumer_app_private_key_stage
          - source: secret/registries-modernization/prod/backpack-registrychecklists/backpackregistrychecklists
            path: backpack_registrychecklists_app_private_key_prod
          - source: secret/registries-modernization/prod/backpack-registrychecklists/backpackregistrychecklistsconsumer
            path: backpack_registrychecklists_consumer_app_private_key_prod
          - source: secret/registries-modernization/prod/backpack-registrychecklists/backpackregistrychecklistsmigrationconsumer
            path: backpack_registrychecklists_migration_consumer_app_private_key_prod
