micronaut:
  application:
    name: backpack-registrychecklists-consumer
  server:
    host: ${backpack-registrychecklists-consumer-host:localhost}
    port: 8080
    idle-timeout: 2000ms
  metrics:
    binders:
      web:
        enabled: false # we are using our own binder via our custom micronaut-metrics lib

postgres:
  max-db-pool-size: 10
  min-db-pool-size: 5

filter:
  server:
    order:
      lists-brave-tracing-server-filter: 100
      lists-traceid-filter: 101
      list-authorization-filter: 200
      registry-channel-subchannel-filter: 400
  client:
    order:
      lists-brave-tracing-client-filter: 900
      resilience-client-filter: 800
      oauth-filter: 701
      oauth-key-filter: 700

components:
  server:
    list-authorization-filter:
      enabled: false
    sanitizing-filter:
      enabled: false
    registry-channel-subchannel-filter:
      enabled: false

msgbus:
  source: backpack-registrychecklists
  dlq-source: backpackregistrychecklists-dlq
  kafka:
    consumer:
      enabled: true
    producer:
      enabled: true
      client-id: backpack-registrychecklists-con-msg-bus-producer
    dlqconsumer:
      enabled: true
    dlqproducer:
      enabled: true
      client-id: backpack-registrychecklists-con-dlq-producer
    topic: registry-internal-data-bus-stage
    consumer-group: backpack-registrychecklists-con-msg-bus-consumer
    consumer-batch-size: 10
    dlq-topic: registry-internal-data-bus-stage-dlq
    dlq-consumer-group: backpack-registrychecklists-con-dlq-consumer
    dlq-event-retry-interval-secs: 1
    dlq-max-event-retry-count: 3
    dlq-consumer-batch-size: 10

kafka-sources:
  allow:
    - backpack-registry
    - backpack-registrychecklists
    - backpackregistrychecklists-migration
    - backpackregistry-migration-stage

kafka:
  bootstrap:
    servers: kafka-ttc-app.dev.target.com:9093
  ssl:
    endpoint.identification.algorithm: ""# disable karka broker cert's hostname verification
    keystore:
      location: /lists-bus-keystore.jks
      password: ${kafka-secret.keystore-password}
    truststore:
      location: /client-truststore.jks
      password: ${kafka-secret.truststore-password}
      type: PKCS12
  security:
    protocol: ssl
  consumers:
    backpack-registrychecklists-con-msg-bus-consumer:
      key:
        deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value:
        deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    backpack-registrychecklists-con-dlq-consumer:
      key:
        deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value:
        deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
  producers:
    # default is a Jackson based JSON serializer for key/value
    backpack-registrychecklists-con-msg-bus-producer:
      retries: 3
      retry:
        backoff:
          ms: 1000
      max:
        in:
          flight:
            requests:
              per:
                connection: 1
        block:
          ms: 2000
